apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: yzk4mgcnk-python 
  janus-idp.io/tekton: yzk4mgcnk-python
  backstage.io/kubernetes-id: yzk4mgcnk-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: yzk4mgcnk-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml