apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yzk4mgcnk-python
  janus-idp.io/tekton: yzk4mgcnk-python
  backstage.io/kubernetes-id: yzk4mgcnk-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: yzk4mgcnk-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
